on:
  release:
    types: [published]


name: Build and Release

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Build the Project
        run: |
          dotnet build

      - name: Test the Project
        run: |
          dotnet test

      - name: Pack the Project
        run: |
          dotnet pack -p:version=echo ${{ github.event.release.tag_name }}/v/
          
      - name: Publish to Nuget
        run: |
          dotnet nuget push "ParndanaLabs.Lib.GtfsRealtimeModels" --api-key ${{secrets.MY_NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json